### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by kewou** [kewou/GestionLoyer#11]
- contrôle des informations reçu via le front
- envoyer l'email de l'utilisateur

**Comment by cnantch** [comment]
Envoi un mail à tous les administrateurs du site (premier temps : adresse de Joel)
vérifier les inputs (côté front)

**Comment by kewou** [comment]
On ne fait pas confiance au Front, les infos doivent être doublement vérifiées

**Comment by kewou** [comment]
Le design des messages d'erreur est à revoir, le background color en rouge, je préfère simple comme sur les autres formulaires

**Comment by cnantch** [comment]
@kewou tu me fais les retours de la PR côté front, sur la PR côté back?

**Comment by kewou** [comment]
Effectivement je me suis loupé

**Comment by kewou** [comment]
Done
