### ISSUE TITLE
Audit sur la gestion des exceptions

### ISSUE THREAD

**Issue by kewou** [kewou/GestionLoyer#6]
check si la gestion des exception est correct, du lancement ainsi que la centralisation via la classe ApiHandleException

**Comment by cnantch** [comment]
n'est t-il pas mieux de centraliser les business exceptions pour faire un gestion unique des custom exceptions que tu as créé

genre dans le ApiHandleException, voir si on peut gérer une business Exception (type not found, internal server, unauthorized, etc..)
Si c'est ok pour toi, je centraliserai tout çà

**Comment by kewou** [comment]
ok pour la centralisation.
